import { Inter } from "next/font/google";
import "./globals.css";
import Login from "./components/login";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ITCrowd Test",
  description: "Generated by Enzo Ariel Fiol",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Login />
        {children}
      </body>
    </html>
  );
}
